# Generated by Django 5.0.3 on 2024-05-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=0, upload_to='photos'),
            preserve_default=False,
        ),
    ]
