# Generated by Django 5.0.3 on 2024-05-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('hall', 'number', 'row')},
        ),
    ]
